[request.florp]
uri = "http://localhost:5284/echo"
method = "Get"
body = "{}"
content_type = "application/json"
headers = { Authorization = "Bearer bloop" }

[[request.florp.post_process]]
variable = "yep"
jpath = "$.headers.Host[0]"

[request.bloop]
uri = "https://localhost"

[request.google]
uri = "https://www.google.com"

[request.somejson]
uri = "https://stackoverflow.com/api/recent-chat"

[[request.somejson.post_process]]
variable = "activeUsers"
jpath = "$.activeUsers"

[request.testforecast]
uri = "https://localhost:7284/weatherforecast"

[request.echo]
uri = "https://localhost:7284/echo"
headers = { X-Derp = "${activeUsers} ${yep}" }

[request.echoquery]
uri = "http://localhost:5284/echo/query?something=${activeUsers}"

[variable.yep]
source = "florp"

[variable.activeUsers]
source = "somejson"
