[request.florp]
uri = "http://localhost:5284/echo"
method = "Get"
body = "{}"
content_type = "application/json"
headers = { Authorization = "Bearer bloop" }

[request.google]
uri = "https://www.google.com"

[request.somejson]
uri = "https://stackoverflow.com/api/recent-chat"

[request.testforecast]
uri = "http://localhost:5284/weatherforecast"

[request.echo]
uri = "http://localhost:5284/echo"
headers = { X-Derp = "${activeUsers} ${yep}" }

[request.echoquery]
uri = "http://localhost:5284/echo/query?something=${activeUsers}"

[request.echocommand]
uri = "http://localhost:5284/echo/query?something=${command}"

[variable.yep]
source = "florp"
jpath = "$.headers.Host[0]"

[variable.activeUsers]
source = "somejson"
jpath = "$.activeUsers"

[variable.command]
command = "./scripts/testVariableScript.ps1"
